project:
  type: book

book:
  title: "Papers para el TFM"
  author: "Pablo Magariños Docampo"
  date: "05/07/2025"
  chapters:
    - index.qmd
    - part: "Graph Neural Networks"
      chapters:
      - Contenido/graph-neural-networks.qmd
    - part: "Real-Time Reinforcement Learning"
      chapters:
      - Contenido/real-time-rl.qmd
    - references.qmd

bibliography: references.bib
csl: estilos/ieee.csl

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



